# -*- coding: utf-8 -*-
"""TesteNAVI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qjo8tGDjic_IH40YPo_uZdHDFl9tm4rv
"""

import numpy as np
import math

# Vetores

divisorespares =[]

# intervalos com números pares

intervalo = np.arange(2, 5000000, 2)

# Descobrindo se é divisível por 37 e 49,

for n in intervalo:
  if n%(37*49)==0:
    divisorespares.append(n)

print("O número de divisores pares são:", len(divisorespares))

vetor = np.empty(10)

#espaços doo vetor

espaços = np.arange(0, 9, 1)

#analisando se o espaço do vetor é impar ou par

for i in espaços:
    if i%2 ==0:
      n = pow(3,i) + 7*math.factorial(i)
      vetor[i] = (n)
    else:
      n = pow(2,i)+ 4*np.log(i)
      vetor[i] = n

# calculo da média      
media = sum(vetor)/(len(vetor))
print("média dos elementos contidos no vetor:", round(media,2))

print()

# Posição do maior valor dentro do vetor
posição = list(vetor).index(max(vetor))

print("Posição do maior elemento:", posição)

#dicionário
notas={}

#Inserindo a nota de cada aluno

notanorberto = float(input("Digite a nota de Norberto: "))
notaivonete = float(input("Digite a nota de Ivonete: "))
notaguilherme = float(input("Digite a nota de Guilherme: "))
notaisabel = float(input("Digite a nota de Isabel: "))
notatheodoro = float(input("Digite a nota de Theodoro: "))

#Adicionando os nomes e notas no dicionário

notas['Norberto'] = notanorberto
notas['Ivonete'] = notaivonete
notas['Guilherme'] = notaguilherme
notas['Isabel'] = notaisabel
notas['Theodoro'] = notatheodoro

print()
print("Aluno com a maior nota e sua respectiva nota")
print()
maximo = max(notas, key=notas.get)

print("Aluno:", maximo)
print("Nota:",notas[maximo])